#!/bin/sh
#/etc/init.d/pi-remote

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec sudo forever --sourceDir=/home/pi/pi-remote -p /root/.forever app.js >> /home/pi/pi-remote/forever.log 2>>/home/pi/pi-remote/err.log &
  ;;
stop)
  exec sudo forever stop 0
  ;;
*)
  echo "Usage: /etc/init.d/pi-remote {start|stop}"
  exit 1
  ;;
esac

exit 0
